name: cola.Provider
stereotype: class
super: cola.Definition
label: 数据提供器
description: 数据提供器的作用是通过Ajax为数据模型提供数据。

attributes:
  - name: url
    type: string
    label: Ajax服务的URL
  - name: loadMode
    type: string
    label: Ajax服务的URL
  - name: method
    type: string
    enum:
      - GET
      - POST
    defaultValue: GET
    label: Ajax请求的类型

  - name: parameter
    type: any
    label: 要随Ajax请求发送的参数

  - name: ajaxOptions
    type: json
    label: 传递给内部使用的jQuery.ajax方法的更多选项

  - name: pageSize
    type: number
    label: 对于集合型数据而言，进行分页装载时每一页的大小

events:
  - name: beforeSend
    label: 请求发送之前触发的事件
    arguments:
      - name: self
        type: cola.Provider
        label: Provider本身
      - name: arg
        properties:
          - name: options
            type: json
            description: 内部调用jQuery.ajax()时使用的选项参数。

  - name: complete
    label: 请求结束之后（无论成功或失败）触发的事件
    arguments:
      - name: self
        type: cola.Provider
        label: Provider本身
      - name: arg
        properties:
          - name: options
            type: json
            description: 内部调用jQuery.ajax()时使用的选项参数。
          - name: success
            type: boolean
            description: 本次请求是否执行成功。
          - name: result
            type: any
            description: 请求成功后Server端返回的结果

  - name: success
    label: 请求成功结束时触发的事件
    arguments:
      - name: self
        type: cola.Provider
        label: Provider本身
      - name: arg
        properties:
          - name: options
            type: json
            description: 内部调用jQuery.ajax()时使用的选项参数。
          - name: result
            type: any
            description: 请求成功后Server端返回的结果

  - name: error
    label: 请求失败时触发的事件
    arguments:
      - name: self
        type: cola.Provider
        label: Provider本身
      - name: arg
        properties:
          - name: options
            type: json
            description: 内部调用jQuery.ajax()时使用的选项参数。